version: 1
worker:
  managed: true
  name: worker-libreflare-template
  domain: example.com
  routePrefix: /logging-route
logging:
  managed: true
  apiUrl: https://logs.example.com/insert/jsonline?_stream_fields=stream
  sourceKey: example-general
  varyByMonth: false
  auth: true
rewriteRule:
  version: 1
  expression: cf.tls_cipher ne ""
